# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true        # automatyczne wstrzykiwanie zależności
        autoconfigure: true   # automatyczne tagowanie (commands, event subscribers itd.)

    # automatyczna rejestracja klas z src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Tests/'
            - '../src/Kernel.php'

    # opcjonalnie: jeśli używasz API Platform extension
    App\Doctrine\Extension\CurrentUserExtension:
        tags:
            - { name: 'api_platform.doctrine.orm.query_extension.collection', priority: 64 }
            - { name: 'api_platform.doctrine.orm.query_extension.item', priority: 64 }
